#ifndef _RANDOM_OS_ERROR_TYPES_H
#define _RANDOM_OS_ERROR_TYPES_H

typedef enum Error {
	VBE_NOT_SUPPORTED_ERROR,
	VBE_SETUP_ERROR,
	USB_TD_BITSTUFF_ERROR,
	USB_TD_TIMEOUT_ERROR,
	USB_TD_BABBLE_ERROR,
	USB_TD_DATA_BUFFER_ERROR,
	USB_TD_STALLED_ERROR,
	USB_TD_NAK_ERROR,
	USB_ALLOC_QH_ERROR,
	USB_ALLOC_TD_ERROR,
	USB_MISSED_MICRO_FRAME_ERROR,
	USB_TRANSACTION_ERROR,
	USB_UNEXPECTED_EHCI_QH_SIZE,
	GLYPH_CODE_NOT_RESERVED_ERROR,
	GLYPH_CODE_RESERVED_ERROR,
	UGSM_INCORRECT_GLYPH_SET_SIZE_ERROR,
	UGSM_GLYPH_NOT_RESERVED_BUT_WE_TRY_USE,
	ACPI_S5_PARSE_ERROR,
	ACPI_S5_NOT_PRESENT_ERROR,
	ACPI_DSDT_ERROR,
	ACPI_NO_VALID_FACP_PRESENT_ERROR,
	ACPI_NO_ACPI_ERROR,
	ACPI_CANNOT_BE_ENABLED_ERROR,
	ACPI_NO_KNOWN_WAY_TO_ENABLE_ACPI_ERROR,
	ACPI_SHUTDOWN_ERROR,
	ACPI_UNABLE_TO_SHUTDOWN_ERROR,
	X16_BIT_EMULATOR_ERROR,
	MEMORY_LACK_ERROR,
	INVALID_ARGUMENT_ERROR,
	UNKNOWN_ERROR
} Error;

#endif