#ifndef _RANDOM_OS_FATAL_ERROR_H
#define _RANDOM_OS_FATAL_ERROR_H

#include "core/types.h"

typedef enum FatalErrorType {
	DIVISION_BY_ZERO_FATAL_ERROR, 				// n / 0 error
	// Reserved ISR 0x1
	NON_MASKABLE_INTERRUPT_FATAL_ERROR = 0x2,	// NMI, вызывается даже при cli ( CLEAR INTERRUPT FLAG )
	BREAK_POINT_FATAL_ERROR,					// 
	STACK_OVERFLOW_FATAL_ERROR,
	INDEX_OVERPOWERED_FATAL_ERROR,
	INVALID_INSTRUCTION_FATAL_ERROR,
	NO_COPROCESSOR_FATAL_ERROR,
	DOUBLE_FAULT_FATAL_ERROR,
	COPROCESSOR_SEGMENT_OVERRUN_FATAL_ERROR,
	INVALID_TSS_FATAL_ERROR,
	SEGMENT_PRESENT_FATAL_ERROR,
	STACK_SEGMENT_FATAL_ERROR,
	GENERAL_PROTECTION_FATAL_ERROR,
	PAGE_FATAL_ERROR,
	RESERVED_FATAL_ERROR,
	X87_FPU_FATAL_ERROR,
	ALIGNMENT_CHECK_FATAL_ERROR,
	MACHINE_CHECK_FATAL_ERROR,
	SIMD_FLOAT_FATAL_ERROR,
	// Reserved ISR 0x14-0x1F
	ISR_KERNEL_UNUSED_FATAL_ERROR = 0x20 // KERNEL DEFINABLE ISR 0x20-0xFF
} FatalErrorType;

int8* getFatalErrorDescription(FatalErrorType errorType);

void causeFatalError(FatalErrorType errorType);

#endif