#ifndef _R_OS_EXCEPTION_ERROR_TYPES_H
#define _R_OS_EXCEPTION_ERROR_TYPES_H

#define ERROR_FIRST ERROR_VBE_NOT_SUPPORTED

#define ERROR_LAST ERROR_UNKNOWN

typedef enum Error {
	ERROR_DIVISION_BY_ZERO,
	ERROR_INVALID_ARGUMENT,
	ERROR_VBE_NOT_SUPPORTED,
	ERROR_VBE_SETUP,
	ERROR_USB_TD_BITSTUFF,
	ERROR_USB_TD_TIMEOUT,
	ERROR_USB_TD_BABBLE,
	ERROR_USB_TD_DATA_BUFFER,
	ERROR_USB_TD_STALLED,
	ERROR_USB_TD_NAK,
	ERROR_USB_ALLOC_QH,
	ERROR_USB_ALLOC_TD,
	ERROR_USB_MISSED_MICRO_FRAME,
	ERROR_USB_TRANSACTION,
	ERROR_USB_UNEXPECTED_EHCI_QH_SIZE,
	ERROR_GLYPH_CODE_NOT_RESERVED,
	ERROR_GLYPH_CODE_RESERVED,
	ERROR_UGSM_INCORRECT_GLYPH_SET_SIZE,
	ERROR_UGSM_GLYPH_NOT_RESERVED_BUT_WE_TRY_USE,
	ERROR_ACPI_S5_PARSE,
	ERROR_ACPI_S5_NOT_PRESENT,
	ERROR_ACPI_DSDT,
	ERROR_ACPI_NO_VALID_FACP_PRESENT,
	ERROR_ACPI_NO_ACPI,
	ERROR_ACPI_CANNOT_BE_ENABLED,
	ERROR_ACPI_NO_KNOWN_WAY_TO_ENABLE_ACPI,
	ERROR_ACPI_SHUTDOWN,
	ERROR_ACPI_UNABLE_TO_SHUTDOWN,
	ERROR_X86EMU_EMULATOR,
	ERROR_MEMORY_LACK,
	ERROR_UNKNOWN
} Error;

#endif