#ifndef _RANDOM_OS_WARNING_TYPES_H
#define _RANDOM_OS_WARNING_TYPES_H

#define WARNING_FIRST USB_BABBLE_DETECTED_WARNING

#define WARNING_LAST UNKNOWN_WARNING

#define WARNING_TYPES_DEFINED WARNING_LAST - WARNING_FIRST

typedef enum Warning {
	WARNING_USB_BABBLE_DETECTED,
	WARNING_ALL_GLYPHS_ARE_RESERVED,
	WARNING_REQUIRED_NUMBER_OF_ARGUMENTS_NOT_REACHED,
	WARNING_UNKNOWN_T_TYPE,
	WARNING_FUNCTION_NOT_IMPLEMENTED,
	WARNING_INVALID_ARGUMENT,
	WARNING_UNKNOWN
} Warning;

#endif