#ifndef _RANDOM_OS_BUFFER_FWD_H
#define _RANDOM_OS_BUFFER_FWD_H

typedef enum Buffer_CreationFlags {
	BUFFER_CREATION_STATIC = 	0b00000001,
	BUFFER_CREATION_NO_SEEK = 	0b00000010,
} Buffer_CreationFlags;

typedef enum Buffer_FlagsSeek {
	BUFFER_FLAG_SEEK_BEGIN,
	BUFFER_FLAG_SEEK_POS,
	BUFFER_FLAG_SEEK_END,
} Buffer_FlagsSeek;

typedef enum Buffer_ErrorCode {
	BUFFER_OK,
	BUFFER_ERROR,

	BUFFER_WAIT_BYTES_ERROR,

	BUFFER_SEND_ID_ERROR,
	BUFFER_NEW_ID_ERROR,
	BUFFER_FREE_ID_ERROR,

	BUFFER_CHECKSUM_UNPACK_ERROR,

	BUFFER_LOG_ERROR,

	BUFFER_SIGN_ERROR,
	
	BUFFER_IS_ACTIVE_ERROR,
	BUFFER_WHY_INACTIVE_ERROR,

	BUFFER_OPEN_ERROR,

	BUFFER_READ_ERROR,
	BUFFER_WRITE_ERROR,
	BUFFER_SEEK_ERROR,

	BUFFER_READ_BYTE_ERROR,
	BUFFER_WRITE_BYTE_ERROR,

	BUFFER_FETCH_ERROR,
	BUFFER_FLUSH_ERROR,
	BUFFER_FETCH_COUNT_ERROR,

	BUFFER_RESET_ERROR,
	BUFFER_FREE_ERROR,

	BUFFER_CLOSE_ERROR,

	BUFFER_IS_INVALID_ERROR,

	BUFFER_UNKNOWN_ERROR = 0xFF,
} Buffer_ErrorCode;

typedef enum Buffer_Port {
	BUFFER_PORT_DATA,
	BUFFER_PORT_COMMAND
} Buffer_Port;

typedef struct Buffer Buffer;

#endif